# Generated by Django 4.2.6 on 2023-10-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoConsumible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consumible', models.CharField(max_length=15, unique=True)),
                ('categoria', models.CharField(max_length=25)),
                ('serial', models.CharField(max_length=20, unique=True)),
                ('cantidad_total', models.CharField(max_length=15)),
                ('valor', models.IntegerField()),
                ('descripcion_elemento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoDevolutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_devolutivo', models.CharField(max_length=25, unique=True)),
                ('categoria_devolutivo', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('serial_sena', models.CharField(max_length=20)),
                ('descripcion_devolutivo', models.CharField(max_length=16)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20, unique=True)),
                ('apellido_1', models.CharField(max_length=12)),
                ('apellido_2', models.CharField(max_length=12)),
                ('tipo_documento', models.CharField(max_length=11)),
                ('numero_documento', models.CharField(max_length=12)),
                ('correo_sena', models.EmailField(max_length=254)),
                ('correo_misena', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono_1', models.CharField(max_length=15)),
                ('telefono_2', models.CharField(max_length=15)),
                ('tipo_contrato', models.CharField(max_length=13)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Prestamo', models.DateField()),
                ('fecha_Devolucion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('elemento_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_elemento', to='senaback.elementodevolutivo', to_field='nombre_devolutivo')),
                ('responsable_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_responsable', to='senaback.usuario', to_field='nombre_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('Descripcion', models.CharField(max_length=150)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias_elemento', to='senaback.elementodevolutivo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias_responsable', to='senaback.usuario')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias_serial', to='senaback.elementodevolutivo')),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Entrega', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('elemento_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_elemento', to='senaback.elementoconsumible', to_field='nombre_consumible')),
                ('responsable_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_responsable', to='senaback.usuario', to_field='nombre_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('Descripcion', models.CharField(max_length=150)),
                ('elemento_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas_elemento_devolutivo', to='senaback.elementodevolutivo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas_responsable', to='senaback.usuario')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas_serial', to='senaback.elementodevolutivo')),
            ],
        ),
    ]
