# Generated by Django 4.2.6 on 2023-11-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='valor',
            new_name='valor_devolutivo',
        ),
    ]
