# Generated by Django 4.2.6 on 2023-11-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0002_rename_valor_elementodevolutivo_valor_devolutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementodevolutivo',
            name='valor_devolutivo',
            field=models.IntegerField(),
        ),
    ]
