# Generated by Django 4.2.6 on 2023-11-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0003_alter_elementodevolutivo_valor_devolutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoconsumible',
            name='cantidad_total',
            field=models.IntegerField(),
        ),
    ]
