# Generated by Django 4.2.4 on 2023-10-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0009_alter_elementoconsumible_descripcion_elemento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='cantidad_elementos_disponibles',
            new_name='cantidad_devolutivo_total',
        ),
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='categoria',
            new_name='categoria_devolutivo',
        ),
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='descripcion_elemento',
            new_name='descripcion_devolutivo',
        ),
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='nombre',
            new_name='nombre_devolutivo',
        ),
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='estado',
            new_name='serial_devolutivo',
        ),
        migrations.RenameField(
            model_name='elementodevolutivo',
            old_name='valor',
            new_name='valor_devolutivo',
        ),
        migrations.RemoveField(
            model_name='elementodevolutivo',
            name='cantidad_elementos_total',
        ),
        migrations.RemoveField(
            model_name='elementodevolutivo',
            name='codigo_placa_sena',
        ),
        migrations.RemoveField(
            model_name='elementodevolutivo',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='elementodevolutivo',
            name='serial',
        ),
    ]
